name: Property Connect
favicon: null
layout_spectrum: 0.24322
typography_spectrum: 0.21429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#463f23'
    - '#fdfefe'
    - '#939173'
    - '#b7c4ba'
  brandStrength: 0.10479626525193453
  lightness: 0.8474305826239288
  saturation: 0.06951168994419277
  rhythmicContrast: 0.2789338396396488
purpose: []
